---
deployment:
  tasks:
    - export DEPLOYPATH=/home5/klinikkvik/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R styles.css $DEPLOYPATH
    - /bin/cp -R script.js $DEPLOYPATH
    - /bin/cp -R favicon.svg $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
